Resolves: 커스텀 버튼 컴포넌트 생성 #8
StepUpper/stepup_front pull request #11
Opened 2024-09-09 08:14 UTC by rlawlsdud1

커스텀 버튼 컴포넌트 생성 완료

## 요약

> 커스텀 버튼 컴포넌트 생성 완료

<br/><br/>

## 이슈 번호 또는 링크

Close #8

2024-09-09 09:14 UTC, SSUK-H requested changes
다른 컴포넌트처럼 통일성을 유지하기 위해 label 대신 title로 props를 받아오는 것은 어떨까요?

2024-09-09 09:19 UTC, SSUK-H approved these changes

2024-09-09 09:26 UTC, oneju approved these changes
확인했습니다-!

2024-09-10 01:05 UTC, june-saisquoi approved these changes
확인했습니다!

2024-09-10 01:14 UTC, merged